title: "Imposter Hunt"
description: "The ultimate social deduction game! Find the imposter before it's too late!"
baseurl: "/imposter-hunt"
url: "https://davidpereira2803.github.io"

author:
  name: "David Pereira"
  github: "davidpereira2803"

markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

lang: en_US

# Navigation order
header_pages:
  - index.md
  - HowToPlay.md
  - Privacy.md

exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - .expo/
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - android/
  - ios/
  - src/
  - app/
  - babel.config.js
  - metro.config.js
  - app.json

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
